Redux form
wolox-training/lb-react pull request #6
Opened 2018-09-28 19:02 UTC by LauchaBo

## Summary

- Added redux form

## Trello Card

https://trello.com/c/hcYtSytt/16-redux-iv-redux-form-todo-finger

2018-09-30 02:16 UTC, FrankIglesias requested changes

2018-09-30 02:16 UTC, FrankIglesias commented on tic-tac-toe/src/components/ContactForm/index.js
> +const ContactForm = props => {
use a function instead

2018-09-30 02:16 UTC, FrankIglesias commented on tic-tac-toe/src/components/ContactForm/index.js
> +  // a unique name for the form
remove this comment

2018-09-30 02:16 UTC, FrankIglesias commented on tic-tac-toe/src/components/ContactPage/index.js
> +    // print the form values to the console
remove comment

2018-09-30 02:16 UTC, FrankIglesias commented on tic-tac-toe/src/components/Game/index.js
> +    const squares = [...current.squares.slice()];
remove the slices

2018-09-30 02:16 UTC, FrankIglesias commented on tic-tac-toe/src/components/Game/index.js
> +        history: history.concat([
you can use a shorthand here like 
``` 
[...history, {squares}]
```

2018-09-30 02:16 UTC, FrankIglesias commented on tic-tac-toe/src/components/Game/index.js
> +  debugger //eslint-disable-line
remove debugger

2018-09-30 02:16 UTC, FrankIglesias commented on tic-tac-toe/src/index.js
> +// store.dispatch({ type: 'EDIT_TILE' });
delete commented line

2018-09-30 02:16 UTC, FrankIglesias commented on tic-tac-toe/src/components/ItemList/index.js
> +    fetch(url)
move this to a file named
`src/services/itemService.js`

2018-09-30 02:16 UTC, FrankIglesias commented on tic-tac-toe/src/index.js
> +const App = () => (
use a function insatead of an arrow

2018-10-02 15:10 UTC, LauchaBo commented on tic-tac-toe/src/components/ContactForm/index.js
> +const ContactForm = props => {
If I transform to a function it gets flooded with errors

2018-10-02 22:11 UTC, FrankIglesias approved these changes

2018-10-02 22:11 UTC, FrankIglesias commented
Well done!

2018-10-04 13:19 UTC, merged